Public Class ConstantesAm
    Public Const ADMISIONISTA = 0
    Public Const MEDICO = 37
    Public Const MEDICOES = 38
    Public Const FISIO = 24
    Public Const PARAMEDICO = 43
    Public Const PARAMEDICOENF = 7
    Public Const CONDUCTOR = 15
    Public Const CONTACTO = 12
    Public Const DIA_FESTIVO = "F"
    Public Const DIA_HABIL = "H"
    Public Const TARIFA_TRIPULACION_CREAR = "SP_TRIPULACION_TARIFA_CREAR"
    Public Const TARIFA_TRIPULACION_BUSCAR = "SP_TRIPULACION_TARIFA_BUSCAR ''"
    Public Const TARIFA_TRIPULACION_CARGAR = "SP_TRIPULACION_TARIFA_CARGAR"
    Public Const TARIFA_TRIPULACION_ANULAR = "SP_TRIPULACION_TARIFA_ANULAR "
    Public Const TARIFA_TRIPULACION_RESPONSABLE_BUSCAR = "SP_TRIPULACION_TARIFA_RESPONSABLE_BUSCAR '',"
    Public Const TARIFA_TRIPULACION_RESPONSABLE_CARGAR = "SP_TRIPULACION_TARIFA_RESPONSABLE_CARGAR"
    Public Const MANUAL_TARIFARIO_AM_CREAR = "SP_MANUAL_TARIFARIO_AM_CREAR"
    Public Const MANUAL_TARIFARIO_AM_BUSCAR = "SP_MANUAL_TARIFARIO_AM_BUSCAR '',"
    Public Const MANUAL_TARIFARIO_AM_CARGAR = "SP_MANUAL_TARIFARIO_AM_CARGAR"
    Public Const MANUAL_TARIFARIO_AM_D_CARGAR = "SP_MANUAL_TARIFARIO_AM_D_CARGAR"
    Public Const MANUAL_TARIFARIO_AM_ANULAR = "SP_MANUAL_TARIFARIO_AM_ANULAR "
    Public Const FILTRO_DGVMANUALTARIFARIO = "Descripcion_Pais_origen LIKE '%'$'%' OR Descripcion_Dpto_origen LIKE '%'$'" &
                                         "%' OR  Descripcion_Municipio_origen LIKE '%'$'%' OR  Descripcion_Pais_Destino LIKE '%'$'" &
                                         "%' OR  Descripcion_Dpto_Destino LIKE '%'$'%' OR  Descripcion_Municipio_Destino LIKE '%'$'" &
                                         "%' OR  Descripcion_Institucion_Origen LIKE '%'$'% ' OR  Descripcion_Institucion_Origen LIKE '%'$'" &
                                         "%' OR  Descripcion_Institucion_Destino LIKE '%'$'%' OR  Descripcion_Procedimiento LIKE '%'$'%'"
    Public Const CODIGO_HABILITACION_AM = "SP_CODIGO_HABILITACION_AM"
    Public Const CONTRATO_AM_CREAR = "SP_CONTRATO_AM_CREAR"
    Public Const CONTRATO_AM_BUSCAR = "SP_CONTRATO_AM_BUSCAR '',"
    Public Const CONTRATO_AM_CARGAR = "SP_CONTRATO_AM_CARGAR"
    Public Const CONTRATO_AM_TARIFA_CARGAR = "SP_CONTRATO_AM_TARIFA_CARGAR"
    Public Const CONTRATO_AM_ANULAR = "SP_CONTRATO_AM_ANULAR "
    Public Const CONTRATO_AM_TERMINAR = "SP_CONTRATO_AM_TERMINAR "
    Public Const PACIENTE_CARGAR_AM = "SP_PACIENTES_AM_CARGAR"
    Public Const CONTRATO_INF_AM_CARGAR = "SP_CONTRATO_INF_AM_CARGAR"
    Public Const EPS_AM_BUSCAR = "SP_EPS_AM_BUSCAR"
    Public Const TRASLADO_AM_CARGA = "SP_TRASLADO_AM_CARGAR"
    Public Const MANUAL_TARIFARIO_EPS_AM_BUSCAR = "SP_MANUAL_TARIFARIO_EPS_AM_BUSCAR "
    Public Const CARGO_AM_BUSCAR = "SP_CARGO_AM_BUSCAR "
    Public Const CARGO_AM_CARGAR = "SP_CARGO_AM_CARGAR"
    Public Const TARIFA_TRIPULACION_AM_D_CARGAR = "SP_TARIFA_TRIPULACION_AM_D_CARGAR"
    Public Const ATENCION_AM_CREAR = "SP_ATENCION_AM_CREAR"
    Public Const IDENTIFICACION_AM_BUSCAR = "SP_IDENTIFICACION_AM_BUSCAR "
    Public Const ATENCION_AM_BUSCAR = "SP_ATENCION_AM_BUSCAR '',"
    Public Const ATENCION_AM_CARGAR = "SP_ATENCION_AM_CARGAR"
    Public Const ATENCION_AM_DIAG_CARGAR = "SP_ATENCION_AM_DIAG_CARGAR"
    Public Const FESTIVOS_BUSCAR = "SP_FESTIVOS_BUSCAR"
    Public Const ATENCION_AM_ANULAR = "SP_ATENCION_AM_ANULAR "
    Public Const ATENCION_AM_TARIFA_D_CARGAR = "sp_ATENCION_AM_TARIFA_D_CARGAR"
    Public Const FACTURA_TRASLADO_AM_CARGAR = "SP_FACTURA_TRASLADO_AM_CARGAR"
    Public Const FACTURA_TRASLADO_DETALLE_AM_CARGAR = "SP_FACTURA_TRASLADO_DETALLE_AM_CARGAR"
    Public Const FACTURA_TRASLADO_PIE_DETALLE_AM_CARGAR = "SP_FACTURA_TRASLADO_PIE_DETALLE_AM_CARGAR"
    Public Const FACTURA_TRASLADO_CONSOLIDADO_AM_CARGAR = "SP_FACTURA_TRASLADO_CONSOLIDADO_AM_CARGAR"
    Public Const REPORTE_INF_EMPLEADO_AM_BUSCAR = "SP_REPORTE_INF_EMPLEADO_AM_BUSCAR "
    Public Const REPORTE_INF_EMPLEADO_AM_CARGAR = "SP_REPORTE_INF_EMPLEADO_AM_CARGAR"
    Public Const REPORTE_INF_AM_BUSCAR = "SP_REPORTE_INF_AM_BUSCAR ''"
    Public Const PRECIO_MANUAL_AM_CARGAR = "SP_PRECIO_MANUAL_AM_CARGAR"
End Class
