Public Class Proveedor
    Public Property idProveedor As String
    Public Property codigoPuc As Integer
    Public Property codigoProveedor As Integer
    Public Property formaPago As Integer
    Public Property regimen As Integer
    Public Property ubicacion As Integer
    Public Property codigoDiaEntrega As Integer
    Public Property codigoDiaVencimiento As Integer
    Public Property codigoDiaDevolucion As Integer
    Public Property observacion As String
    Public Property suspendido As Boolean
    Public Property bloqueado As Boolean
    Public Property codigoEp As Integer
    Public Property tipoPago As String
    Public Property banco As Integer
    Public Property TipocuentaBancaria As String
    Public Property numeroCuenta As String
    Public Property identificacionProveedor As String
    Public Property reteIca As Boolean
    Public Property reteFuente As Boolean
    Public Property reteIva As Boolean
    Public Property ctaReteIca As String
    Public Property ctaReteIva As String
    Public Property ctaReteFuente As String
    Public Property idEmpresa As Integer
    Public Property cuentaPuc As String
    Public Property codigoCiiu As String
    Public Property dtPlazo As DataTable
    Public Property usuario As Integer
End Class
