Public Class ConstantesAsis
    Public Const CODIGO_MENU_FACTURA_ASISTENCIAL = "a30401"
    Public Const CODIGO_MENU_FACTURA_EXTERNA = "a30404"
    Public Const CODIGO_MENU_FACTURA_EXTERNA_ATE = "a30405"
    Public Const CODIGO_MENU_FACTURA_EXTERNA_IMA = "a70401"
    Public Const CODIGO_MENU_FACTURA_EXTERNA_LAB = "a90601"
    Public Const CODIGO_MENU_FACTURA_EXTERNA_CEXT = "ag0401"
    Public Const NOMBRE_PDF_FACTURA = "a30404"
    Public Const CODIGO_FACTURA_ASISTENCIAL = "500"

    Public Const TIPO_FACTURA_ASISTENCIAL = 0
    Public Const TIPO_FACTURA_ASISTENCIAL_CTC = 1
    Public Const TIPO_FACTURA_EXTERNA = 2
    Public Const TIPO_FACTURA_AMBULANCIA = 3
    Public Const TIPO_FACTURA_REMISION = 4

    Public Const CODIGO_TARIFA_LABORATORIO = 2
    Public Const CODIGO_TARIFA_PROCEDIMIENTOS = 0
    Public Const INSTITUCION_UCI_SABANA = 11
End Class
