Public Class Mensajes
    'Mensajes predeterminados
    Public Const EN_CONSTRUCCION = "Esta opción se encuentra en desarrollo. Disculpe las molestias."
    Public Const GUARDAR = "¿Desea guardar este registro?"
    Public Const GUARDADO = "¡Registro guardado con éxito!"
    Public Const RIPS = "¡Los rips han sido generado correctamente!"
    Public Const GENERAR = "¿Desea generar los rips?"
    Public Const ENVIAR = "¿Realmente envior el correo?"
    Public Const ANULAR = "¿Desea anular este registro?"
    Public Const TERMINAR_CONTRATO = "¿Desea Terminar este Contrato?"
    Public Const ANULADO = "¡Registro anulado!"
    Public Const EDITAR = "¿Desea editar este registro?"
    Public Const MEDICAMENTO_REEMPLAZAR = "Desea reemplazar este medicamento"
    Public Const CANCELAR = "¿Desea cancelar este registro?"
    Public Const DUPLICAR = "¿Desea duplicar este registro?"
    Public Const TRASLADO_PACIENTE = "¿Desea trasladar este registro?"
    Public Const SALIR = "¿Desea salir de esta ventana?"
    Public Const SINPERMISO = "¡Usted no tiene permiso para esta opción!"
    Public Const SELECCIONE_LISTADO_EMPLEADO = "¡Debe seleccionar el empleado para continuar!"
    Public Const MENSAJE_MANUAL = "¡No se encuentra manual!"
    Public Const QUITAR = "¿Desea quitar la fila seleccionada?"
    Public Const PERFIL_IGUAL = "¡El perfil seleccionado es el mismo del usuario actual!"
    Public Const CODIGO_EXISTE = "¡Este código ya existe!"
    Public Const SELECCIONE_PUNTO_ASIGNADO = "¡Seleccione un punto de servicio asignado a esta empresa!"
    Public Const NO_ANULAR_PUNTO_SERVICIO = "¡No esta permitido anular este punto de servicio!"
    Public Const NO_ANULAR_PACIENTE = "¡No esta permitido anular este paciente, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_AFILIACION = "¡No esta permitido anular esta Afiliaciòn, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_CAUSA_EXTERNA = "¡No esta permitido anular esta Causa Externa, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_CLASE_SOCIAL = "¡No esta permitido anular esta Clase Social, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_TIPO_EXAMEN = "¡No esta permitido anular este tipo examen, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_DESTINO = "¡No esta permitido anular esta destino, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_INSTITUCION = "¡No esta permitido anular esta institución, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_ESPECALIDAD = "¡No esta permitido anular esta especialidad, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_ESTADO_CIVIL = "¡No esta permitido anular este estado civil, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_TIPO_IDENTIFICACION = "¡No esta permitido anular este tipo de identificación, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_OCUPACION = "¡No esta permitido anular esta ocupacion, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_VIA_INGRESO = "¡No esta permitido anular esta via de ingreso, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_PARAMETRO = "¡No esta permitido anular este parametro, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_TIPO_REGIMEN = "¡No esta permitido anular este tipo de regimen, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_ESTADO_ATENCION = "¡No esta permitido anular este estado de atención, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_DIAGNOSTICO = "¡No esta permitido anular diagnostico, Actualmente se encuentra en uso!"
    Public Const NO_ANULAR_CAMA = "¡No esta permitido anular esta cama, Actualmente se encuentra en uso!"
    Public Const SELECCIONE_DIA_ESTANCIA = "¡Por favor seleccione la estancia para este dia!"
    Public Const CAMBIOS_SIN_GUARDAR = "¡Existe cambios sin guardar! Guarde o cancele el registro."
    Public Const CAMBIOS_2DO_SIN_GUARDAR = "¡Existe procesos guardandose en 2do plano¡. Por favor espere"
    Public Const SEGUNDO_PLANO = "Este proceso se realizará en 2do plano. Se abrirá cuando finalice."
    Public Const SELECCIONAR_ITEM = "Por favor seleccionar un grupo a configurar"

    'Mensajes Historia Clínica
    Public Const FALTA_ESTANCIA = "¡Por favor rectifique los dias de estancia, faltan registros!"
    Public Const MAYOR_REGISTRO_ESTANCIA = "¡Por favor rectifique los dias de estancia, existe un mayor número de registros permitidos!"
    Public Const JUSTIFICAR_ESTANCIA = "¡Por favor justifique la estancia del paciente!"
    Public Const FECHA_MENOR_INGRESO = "¡Por favor seleccione una fecha valida! No puede ser menor a el ingreso del paciente."
    Public Const FECHA_MAYOR_PERMITIDA = "¡Por favor seleccione una fecha valida! No puede ser mayor a 1 dia de adelanto."
    Public Const FECHA_MAYOR_EPICRISIS = "¡Por favor seleccione una fecha valida! No puede ser mayor a el egreso del paciente u hora actual. "
    Public Const INTERVALO_MAYOR_HORAS = "¡Por favor seleccione una hora valida! Diferencia máxima 5 horas a la actual. "
    Public Const INTERMEDIO_MAYOR_HORAS = "¡Por favor seleccione una hora valida! Diferencia para una orden medica intermedia no puede ser mayor a 2 horas."
    Public Const HORA_MENOR_INGRESO = "¡Por favor seleccione una hora valida! No puede ser menor a el ingreso del paciente."
    Public Const HORA_MAYOR_EPICRISIS = "¡Por favor seleccione una hora valida! No puede ser mayor a el egreso del paciente u hora actual."
    Public Const EXISTE_ESTANCIA = "¡Por favor seleccione una fecha valida! Ya existe estancia para este dia."
    Public Const COMIDA_HORA_NO_PERMITIDA = "¡La hora actual no permite seleccionar esta comida!"
    Public Const COMIDA_NO_SELECCIONADA = "¡Por favor seleccione por lo menos una hora para aplicar la comida!"
    Public Const QUITAR_DISOLVENTE = "¿Desea no aplicar disolvente? si tiene mezcla, tambien eliminará."
    Public Const APLICAR_DISOLVENTE = "¡Debe seleccionar disolvente.!"
    Public Const REPORTE_EN_PROGRESO = "¡Por favor intentelo mas tarde, este reporte se encuentra en progreso.!"
    Public Const DIGITE_PESO_PACIENTE = "¡Por favor digite cantidad válida para el peso del paciente!"
    Public Const FECHA_PRIMERA_ORDEN_PACIENTE = "¡No se puede modificar la fecha de la primera orden del paciente!"
    Public Const ESCOGE_MODO_VENTILACION = "¡Debe escoger el modo de ventilacion antes de editar las fechas!"
    Public Const TEMPERATURA_NO_VALIDA = "¡Por favor, verifique la temperatura, "
    Public Const FECHA_FINAL_MAYOR = "¡La fecha final tiene que ser mayor a la inicial!"
    Public Const FECHA_NO_VALIDA = "¡Fecha no valida!"
    Public Const FECHA_EGRESO_MENOR = "¡No se puede colocar fila por favor rectifique fecha egreso!"
    Public Const FORMATO_OBLIGATORIO = "Para este procedimiento se hace necesario la realización de Informe. ¿Continuar?"
    Public Const FORMATO_INGRESO = "Existe un formato de ingreso para la patología de este paciente. ¿desea aplicarlo?"
    Public Const SOLICITUD_NO_POS = "Este medicamento es NO POS, hace necesario la realización de la solicitud. ¿Continuar o Cancelar para Suspender?"
    Public Const JUSTIFICACION_ANTIBIOTICO = "Este medicamento es especial, hace necesario la realización de la solicitud. ¿Continuar  o Cancelar para Suspender?"
    Public Const QUITAR_PROCEDIMIENTO = "No ha guardado, Si continua no se enviará este procedimiento ¿Desea continuar?"
    Public Const QUITAR_MEDICAMENTO = "No ha guardado, Si continua no se enviará este medicamento ¿Desea continuar?"
    Public Const NO_POS_NO_EVOLUCIONES = "¡No se puede hacer la solicitud del medicamento NO POS, si el paciente no tiene evoluciones medicas!"
    Public Const NO_JUSTIFICAR_NO_EVOLUCION = "¡No se puede justificar el medicamento especial, si el paciente no tiene evoluciones medicas!"
    Public Const CANTIDAD_VALIDA = "¡Por favor digite una cantidad valida!"
    Public Const JUSTIFICACION_TERAPIA_FISICA = "¡ Por favor ingrese la justificación de las terapias fisicas !"
    Public Const PESO_INVALIDO = "¡Debe colocar el peso del paciente!"
    Public Const CANTIDAD_DE_AGUA_INVALIDA = "¡El agua destilada no puede ser un valor por debajo de 0!" & vbNewLine & "Revise y ajustes los requerimientos de cada item."
    Public Const HORA_INICIO_INVALIDA = "¡Por favor elija la hora de inicio de la nutrición!"
    Public Const HORA_INICIO_MED_INVALIDA = "¡Por favor corrija la hora de inicio del medicamento! no puede ser vacia ni inferior a la admisión."
    Public Const HORA_INICIO_IMP_INVALIDA = "¡Por favor corrija la hora de inicio de la impregnación! no puede ser vacia ni inferior a la admisión."
    Public Const HORA_INICIO_INF_INVALIDA = "¡Por favor corrija la hora de inicio de la infusión! no puede ser vacia ni inferior a la admisión."
    Public Const HORARIO_INVALIDO = "¡Por favor elija horario del medicamento"
    Public Const AGREGAR_PERFIL = "¿Desea agregar procedimientos de este perfil a la orden médica?"
    Public Const OXIGENO_INCORRECTO = "Rectifique la grilla de oxigeno"
    Public Const APROBAR_REVISION = "¿Desea aprobar el cierre de todos los pacientes OK?"
    Public Const APROBAR_REVISION_UNICA = "¿Desea aprobar el cierre de este paciente?"

    'Mensajes de inventario
    Public Const MSM_NOMBRE = "¡Debe ingresar el nombre!"
    Public Const MAYOR_STOCK = "¡La cantidad ingresada es mayor al stock actual!"
    Public Const MAYOR_CANTIDAD_PEDIDA = "¡la cantidad ingresada es mayor a la cantidad pedida!"
    Public Const INGRESO_PRODUCTOS_VALIDACION = "¡Debe ingresar por lo menos un producto!"
    Public Const BODEGAS_ESCOGIDAS = "¡Debe escoger por lo menos una bodega!"
    Public Const ESCOGER_PEDIDO_SERVCIO = "¡Debe escoger un pedido de servicio!"
    Public Const COLOCAR_HORA_INICIAL = "No se ha colocado la hora inicial a los todos lo medicamentos !"
    Public Const VALOR_PERMITIDO = "¡Por favor escriba una cantidad valida!"
    Public Const MSM_CANTIDAD_DESAYUNO = "Desayunos = "
    Public Const MSM_CANTIDAD_ALMUERZOS = "Almuerzos = "
    Public Const MSM_CANTIDAD_CENAS = "Cenas = "
    Public Const MSM_CANTIDAD_TOTALES = "Total Comidas = "
    Public Const MSM_RECONSTITUYENTE_NECESARIO_PEMS = "¡Debe escoger el reconsituyente antes de colocar la cantidad!"
    Public Const MSM_DILUYENTE_DOSIS_UNITARIA = "¡No se puede escoger el reconstituyente o diluyente antes de colocar la dosis del medicamento!"
    Public Const MSM_DOSIS_NECESARIA = "¡Debe ingresar la dosis del medicamento!"
    Public Const MSM_VELOCIDAD_NECESARIA = "¡Debe escoger la velocidad (CC/Hr)!"
    Public Const MSM_PEMS_MANUAL = "¿Desea realizar el pems manual?"
    Public Const MSM_DILUYENTE_NECESARIO_PEMS = "¡Debe escoger el diluyente antes de colocar la cantidad!"
    Public Const MSM_CONTRATOS_SIN_VIGENCIA = "¡No hay contrato vigente para este cliente!"
    Public Const ANULAR_AJUSTE_INVENTARIO_NO_PERMITIDO = "¡No se puede anular este ajuste, daria valores negativos en stock!"
    Public Const QUITAR_LOTE = "¿Desea quitar los lotes de lotes de este producto? "
    Public Const NO_ANULAR_RECEPCION_TECNICA = "¡No se puede anular la recepción, Hay movientos en los lotes recepcionados!"
    Public Const MEDICAMENTOS_INSUMOS_FALTANTES_DESPACHO_PEM = "Debe despachar por lo menos un medicamento o insumo ! "
    Public Const NO_SUPERAR_CANTIDAD_ENTREGADA_DEVOLUCION_PEM = "La cantidad o concentración a devolver no puede ser mayor a la cantidad o concentración despachada !"
    Public Const NO_ANULAR_PEM = "No se puede anular este pem ya que ha sido despachado!"
    'mensaje archivo
    Public Const SELECCIONAR_FACTURA = "¡Favor seleccionar alguna factura!"
    Public Const QUITAR_LIQUIDO = "¿Desea quitar el liquido de dilución?"
    Public Const SELECCIONAR_CLIENTE = "¡Favor seleccionar un cliente!"

    Public Const SOLICITUD_LAB_EXISTENTE = "¡No se puede editar o eliminar Ordenes que tengan solicitud a laboratorio o pedido a farmacia!"
    Public Const DESPACHO_CANTIDAD_MAYOR_A_STOCK = "¡La cantidad ingresada no puede ser mayor al stock disponible!"
    Public Const CAMBIO_VISADO = "¿Desea cambiar el visado de la admisión?"
    Public Const EDITAR_HORAS_MEDICAMENTO = "¡Recuerde, Solo puede editar horas de aplicación y/o enviar comidas!"

    'Contabilidad
    Public Const CONTA_RESULTADO_VACIO = "¡No se encontraron resultados para el tercero y periodo seleccionado!"
    Public Const CONTA_TERCERO_INEXISTENTE = "¡No se encontró tercero especificado!"
    Public Const CONTA_CUENTA_PUC_INEXISTENTE = "¡No se encontró la cuenta especificada!"
    '--------------
    Public Const PROGRAMACION_TAREAS_PENDIENTES = "Se registró con ¡èxito!, algunas tareas para el paciente: "
    '-----------
    Public Const VERIFICACION_DOCUMENTO = "¡Ya,se encuentra un paciente con la siguiente identificación! "
    '----- FACTURACION
    Public Const VALORES_EN_CERO = "¡Valores en 0. Se deben corregir antes de continuar!"
    Public Const FECHA_FIN_CONTRATO = "¡Fecha final del contrato superada!"
    Public Const LIMITE_ATENCION_CONTRATO = "¡Cantidad máxima de facturas realizadas para el contrato!"
    Public Const VALOR_FIN_CONTRATO = "¡Valor del contrato superado!"
    Public Const LIMITE_RESOLUCION = "¡Fecha o consecutivo de la resolucion superada!"

    '------ NOMINA
    Public Const IMPOSIBLE_ANULAR_NOMINA = "¡Ya se ha realizado el pago a la nómina. Comuníquese con el área contable!"
    Public Const IMPOSIBLE_GUARDAR_NOMINA = "¡No existen registros para guardar!"
    Public Const IMPOSIBLE_IMPRIMIR_NOMINA = "¡No existen registros para el reporte!"
    Public Const IMPOSIBLE_GUARDAR_NOMINA_EXISTENTE = "¡Ya existe una nómina de todo el mes!"
    Public Const IMPOSIBLE_GUARDAR_NOMINA_ANTERIOR_EXISTENTE = "¡No se han realizado nóminas anteriores!"
    Public Const IMPOSIBLE_GUARDAR_NOMINA_EMPLEADO_ERROR = "¡Por favor corregir o quitar empleados con errores para poder continuar!"
    Public Const IMPOSIBLE_GUARDAR_NOMINA_SUPERIOR = "¡El mes de la nómina es mayor al actual!"
    Public Const IMPOSIBLE_GUARDAR_CAUSACION_NOMINA = "¡La diferencia debe ser igual a 0!"
    Public Const IMPOSIBLE_GUARDAR_CAUSACION_NOMINA_NO_CUENTA = "¡Existen terceros sin codigo de cuenta o la diferencia en su movimiento es diferente de 0!"
    Public Const PERIODO_CONTABLE_CERRADO = "¡Periodo de fecha cerrado!"
    Public Const COMPROBANTE_ANULADO = "¡Comprobante Anulado!"

    Public Const IMPOSIBLE_ANULAR_DEDUCCION = "¡Ya se ha realizado el pago de alguna cuota. Comuníquese con el área de Sistemas!"
    Public Const IMPOSIBLE_ANULAR_MOVIMIENTO = "¡Este movimiento ya se ha aplicado. Comuníquese con el área de Sistemas!"
    Public Const GUARDE_ANTES_PARA_EFECTUAR = "Puede que deba guardar antes para que se haga efectivo el cambio"
    Public Const CAMBIAR_PAGO = "¿Desea cambiar el estado de este registro?"
    Public Const MEDICAMENTOS_AUTOMATICOS = "¡Se enviarán medicamentos ordenados por (36,48,72 Horas). Por favor rectifique!"
    Public Const PROCEDIMIENTOS_AUTOMATICOS = "¡Se enviarán procedimientos automáticos! "
    Public Const MEDICAMENTOS_AUDITORIA_AUTOMATICOS = "¡Se enviarán medicamentos configurados! "
    Public Const PROHIBIDO_ANULAR_HORARIO = "El Horario no se puede Anular"
    Public Const HORARIO_EXISTENTE = "¡Ya existe un Cuadro de Turnos Para este mes!"
    Public Const ASIGNE_PUNTO_DE_SERVICIO = "¡Por favor asigne el punto donde laborará!"
    Public Const PROHIBIDO_EDITAR_HORARIO = "¡No tiene permiso para modificar este día!"
    Public Const IMPOSIBLE_GUARDAR_HORARIO = "¡No existen convenciones que guardar!"
    Public Const ESCOGER_CONVENCION = "¡Debe Escoger Una Convencion!"
    Public Const NUEVA_ADMISION = "¡Por favor diligencie la admisión del paciente!"
    Public Const NUEVA_ADMISION_GENERADA = "Nueva Admisión para el paciente: "
    'Public Const IMPRESION_ESPERA = " Favor espere unos, momentos el reporte esta en progreso "
    Public Const VENTANA_ACTIVA = "¡Por favor cierre primero las ventanas activas!"
    Public Const EXONERAR_FACTURA = "¡Atención exonerada satisfactoriamente!"
    Public Const EXONERAR_FACTURA_ATENCION = "¡Factura Atención exonerada satisfactoriamente!"
    Public Const EXONERAR_SIN_MOTIVO = "¡Por favor ingrese alguna observación!"
    Public Const SUPRIMIR_CONVENCION = "Horario Distinto. ¿Está seguro que desea eliminar esta convención?"
    Public Const FORMATO_OBLIGATORIO_PLANTILLA = "Para este Paraclinico se hace necesario la realización de Plantilla Informe Especiales. ¿Continuar?"
    Public Const SOLICITUD_EXAMEN = "¿Esta seguro de enviar la Solicitud para este Examen?"
End Class
